/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StyleguideImport } from './routes/styleguide'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as SidebarImport } from './routes/_sidebar'
import { Route as SidebarIndexImport } from './routes/_sidebar/index'
import { Route as SidebarDashboardIndexImport } from './routes/_sidebar/dashboard/index'
import { Route as SidebarCollectionIndexImport } from './routes/_sidebar/collection/index'
import { Route as SidebarAdminCigarsImport } from './routes/_sidebar/admin/cigars'
import { Route as SidebarAdminBrandsImport } from './routes/_sidebar/admin/brands'
import { Route as SidebarAdminCigarsManageImport } from './routes/_sidebar/admin/cigars/manage'
import { Route as SidebarAdminCigarsCigarIdImport } from './routes/_sidebar/admin/cigars/$cigarId'

// Create/Update Routes

const StyleguideRoute = StyleguideImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const SidebarRoute = SidebarImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRoute,
} as any)

const SidebarIndexRoute = SidebarIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRoute,
} as any)

const SidebarDashboardIndexRoute = SidebarDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => SidebarRoute,
} as any)

const SidebarCollectionIndexRoute = SidebarCollectionIndexImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => SidebarRoute,
} as any)

const SidebarAdminCigarsRoute = SidebarAdminCigarsImport.update({
  id: '/admin/cigars',
  path: '/admin/cigars',
  getParentRoute: () => SidebarRoute,
} as any)

const SidebarAdminBrandsRoute = SidebarAdminBrandsImport.update({
  id: '/admin/brands',
  path: '/admin/brands',
  getParentRoute: () => SidebarRoute,
} as any)

const SidebarAdminCigarsManageRoute = SidebarAdminCigarsManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => SidebarAdminCigarsRoute,
} as any)

const SidebarAdminCigarsCigarIdRoute = SidebarAdminCigarsCigarIdImport.update({
  id: '/$cigarId',
  path: '/$cigarId',
  getParentRoute: () => SidebarAdminCigarsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideImport
      parentRoute: typeof rootRoute
    }
    '/_sidebar/': {
      id: '/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarIndexImport
      parentRoute: typeof SidebarImport
    }
    '/_sidebar/admin/brands': {
      id: '/_sidebar/admin/brands'
      path: '/admin/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof SidebarAdminBrandsImport
      parentRoute: typeof SidebarImport
    }
    '/_sidebar/admin/cigars': {
      id: '/_sidebar/admin/cigars'
      path: '/admin/cigars'
      fullPath: '/admin/cigars'
      preLoaderRoute: typeof SidebarAdminCigarsImport
      parentRoute: typeof SidebarImport
    }
    '/_sidebar/collection/': {
      id: '/_sidebar/collection/'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof SidebarCollectionIndexImport
      parentRoute: typeof SidebarImport
    }
    '/_sidebar/dashboard/': {
      id: '/_sidebar/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SidebarDashboardIndexImport
      parentRoute: typeof SidebarImport
    }
    '/_sidebar/admin/cigars/$cigarId': {
      id: '/_sidebar/admin/cigars/$cigarId'
      path: '/$cigarId'
      fullPath: '/admin/cigars/$cigarId'
      preLoaderRoute: typeof SidebarAdminCigarsCigarIdImport
      parentRoute: typeof SidebarAdminCigarsImport
    }
    '/_sidebar/admin/cigars/manage': {
      id: '/_sidebar/admin/cigars/manage'
      path: '/manage'
      fullPath: '/admin/cigars/manage'
      preLoaderRoute: typeof SidebarAdminCigarsManageImport
      parentRoute: typeof SidebarAdminCigarsImport
    }
  }
}

// Create and export the route tree

interface SidebarAdminCigarsRouteChildren {
  SidebarAdminCigarsCigarIdRoute: typeof SidebarAdminCigarsCigarIdRoute
  SidebarAdminCigarsManageRoute: typeof SidebarAdminCigarsManageRoute
}

const SidebarAdminCigarsRouteChildren: SidebarAdminCigarsRouteChildren = {
  SidebarAdminCigarsCigarIdRoute: SidebarAdminCigarsCigarIdRoute,
  SidebarAdminCigarsManageRoute: SidebarAdminCigarsManageRoute,
}

const SidebarAdminCigarsRouteWithChildren =
  SidebarAdminCigarsRoute._addFileChildren(SidebarAdminCigarsRouteChildren)

interface SidebarRouteChildren {
  SidebarIndexRoute: typeof SidebarIndexRoute
  SidebarAdminBrandsRoute: typeof SidebarAdminBrandsRoute
  SidebarAdminCigarsRoute: typeof SidebarAdminCigarsRouteWithChildren
  SidebarCollectionIndexRoute: typeof SidebarCollectionIndexRoute
  SidebarDashboardIndexRoute: typeof SidebarDashboardIndexRoute
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarIndexRoute: SidebarIndexRoute,
  SidebarAdminBrandsRoute: SidebarAdminBrandsRoute,
  SidebarAdminCigarsRoute: SidebarAdminCigarsRouteWithChildren,
  SidebarCollectionIndexRoute: SidebarCollectionIndexRoute,
  SidebarDashboardIndexRoute: SidebarDashboardIndexRoute,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof SidebarRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/styleguide': typeof StyleguideRoute
  '/': typeof SidebarIndexRoute
  '/admin/brands': typeof SidebarAdminBrandsRoute
  '/admin/cigars': typeof SidebarAdminCigarsRouteWithChildren
  '/collection': typeof SidebarCollectionIndexRoute
  '/dashboard': typeof SidebarDashboardIndexRoute
  '/admin/cigars/$cigarId': typeof SidebarAdminCigarsCigarIdRoute
  '/admin/cigars/manage': typeof SidebarAdminCigarsManageRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/styleguide': typeof StyleguideRoute
  '/': typeof SidebarIndexRoute
  '/admin/brands': typeof SidebarAdminBrandsRoute
  '/admin/cigars': typeof SidebarAdminCigarsRouteWithChildren
  '/collection': typeof SidebarCollectionIndexRoute
  '/dashboard': typeof SidebarDashboardIndexRoute
  '/admin/cigars/$cigarId': typeof SidebarAdminCigarsCigarIdRoute
  '/admin/cigars/manage': typeof SidebarAdminCigarsManageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_sidebar': typeof SidebarRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/styleguide': typeof StyleguideRoute
  '/_sidebar/': typeof SidebarIndexRoute
  '/_sidebar/admin/brands': typeof SidebarAdminBrandsRoute
  '/_sidebar/admin/cigars': typeof SidebarAdminCigarsRouteWithChildren
  '/_sidebar/collection/': typeof SidebarCollectionIndexRoute
  '/_sidebar/dashboard/': typeof SidebarDashboardIndexRoute
  '/_sidebar/admin/cigars/$cigarId': typeof SidebarAdminCigarsCigarIdRoute
  '/_sidebar/admin/cigars/manage': typeof SidebarAdminCigarsManageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/styleguide'
    | '/'
    | '/admin/brands'
    | '/admin/cigars'
    | '/collection'
    | '/dashboard'
    | '/admin/cigars/$cigarId'
    | '/admin/cigars/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/styleguide'
    | '/'
    | '/admin/brands'
    | '/admin/cigars'
    | '/collection'
    | '/dashboard'
    | '/admin/cigars/$cigarId'
    | '/admin/cigars/manage'
  id:
    | '__root__'
    | '/_sidebar'
    | '/login'
    | '/register'
    | '/styleguide'
    | '/_sidebar/'
    | '/_sidebar/admin/brands'
    | '/_sidebar/admin/cigars'
    | '/_sidebar/collection/'
    | '/_sidebar/dashboard/'
    | '/_sidebar/admin/cigars/$cigarId'
    | '/_sidebar/admin/cigars/manage'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SidebarRoute: typeof SidebarRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StyleguideRoute: typeof StyleguideRoute
}

const rootRouteChildren: RootRouteChildren = {
  SidebarRoute: SidebarRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StyleguideRoute: StyleguideRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_sidebar",
        "/login",
        "/register",
        "/styleguide"
      ]
    },
    "/_sidebar": {
      "filePath": "_sidebar.tsx",
      "children": [
        "/_sidebar/",
        "/_sidebar/admin/brands",
        "/_sidebar/admin/cigars",
        "/_sidebar/collection/",
        "/_sidebar/dashboard/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/styleguide": {
      "filePath": "styleguide.tsx"
    },
    "/_sidebar/": {
      "filePath": "_sidebar/index.tsx",
      "parent": "/_sidebar"
    },
    "/_sidebar/admin/brands": {
      "filePath": "_sidebar/admin/brands.tsx",
      "parent": "/_sidebar"
    },
    "/_sidebar/admin/cigars": {
      "filePath": "_sidebar/admin/cigars.tsx",
      "parent": "/_sidebar",
      "children": [
        "/_sidebar/admin/cigars/$cigarId",
        "/_sidebar/admin/cigars/manage"
      ]
    },
    "/_sidebar/collection/": {
      "filePath": "_sidebar/collection/index.tsx",
      "parent": "/_sidebar"
    },
    "/_sidebar/dashboard/": {
      "filePath": "_sidebar/dashboard/index.tsx",
      "parent": "/_sidebar"
    },
    "/_sidebar/admin/cigars/$cigarId": {
      "filePath": "_sidebar/admin/cigars/$cigarId.tsx",
      "parent": "/_sidebar/admin/cigars"
    },
    "/_sidebar/admin/cigars/manage": {
      "filePath": "_sidebar/admin/cigars/manage.tsx",
      "parent": "/_sidebar/admin/cigars"
    }
  }
}
ROUTE_MANIFEST_END */
