/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CollectionIndexImport } from './routes/collection/index'
import { Route as CollectionAddCigarImport } from './routes/collection/addCigar'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CollectionIndexRoute = CollectionIndexImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRoute,
} as any)

const CollectionAddCigarRoute = CollectionAddCigarImport.update({
  id: '/collection/addCigar',
  path: '/collection/addCigar',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/collection/addCigar': {
      id: '/collection/addCigar'
      path: '/collection/addCigar'
      fullPath: '/collection/addCigar'
      preLoaderRoute: typeof CollectionAddCigarImport
      parentRoute: typeof rootRoute
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection/addCigar': typeof CollectionAddCigarRoute
  '/collection': typeof CollectionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection/addCigar': typeof CollectionAddCigarRoute
  '/collection': typeof CollectionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/collection/addCigar': typeof CollectionAddCigarRoute
  '/collection/': typeof CollectionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collection/addCigar' | '/collection'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection/addCigar' | '/collection'
  id: '__root__' | '/' | '/collection/addCigar' | '/collection/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionAddCigarRoute: typeof CollectionAddCigarRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionAddCigarRoute: CollectionAddCigarRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/collection/addCigar",
        "/collection/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/collection/addCigar": {
      "filePath": "collection/addCigar.tsx"
    },
    "/collection/": {
      "filePath": "collection/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
